### ISSUE TITLE
"Task" chapter only has placeholder content

### ISSUE THREAD

**Issue by tpoindex** [evancz/guide.elm-lang.org#109]
https://guide.elm-lang.org/error_handling/task.html  has a placeholder ("updating for 0.18"), no real content.  Since I don't have any Elm usage prior to 0.18, it would be nice to have this chapter published.

**Comment by cllns** [comment]
Agreed, came here to file this issue but it already exists. Looks like it's been gone for over a year now ([since Nov 13, 2016](https://github.com/evancz/guide.elm-lang.org/commit/1881cc730e0dc2f6df5e2b9514a7079b68344043#diff-df91c23b1cd155845137e7abf329e0ae)).

I'm happy to help with this. I'd open a PR for this but since I'm new to Elm, I'm not the best person to do that. Happy to help in terms of editing, proofreading, etc. though.

**Comment by evancz** [comment]
This has been resolved by the recent rewrite of the book.
