### ISSUE TITLE
Is the type of view in the Javscript Interop example wrong?

### ISSUE THREAD

**Issue by bitterjug** [evancz/guide.elm-lang.org#14]
The Javascript Interop example [imports `Html.App as Html`](https://github.com/evancz/guide.elm-lang.org/blame/master/interop/javascript.md#L32). Does that mean that the [type of `view`](https://github.com/evancz/guide.elm-lang.org/blame/master/interop/javascript.md#L93) (`Html Msg`) is effectively 

    Html.App Msg

Instead of 

    Html.Html Msg

Which is what I think it needs to be.

**Comment by evancz** [comment]
That's not how it works. Please ask on elm-discuss or the Elm slack channel (http://elm-lang.org/community) for more explanation!

**Comment by bitterjug** [comment]
Since this is an educational example, _That's not how it works_ doesn't feel like a satisfactory explanation. I appreciate that this issue might not be your preferred forum for this question but I was hoping that by asking it here the answer might serve to help others who might find this puzzling.

**Comment by bitterjug** [comment]
Okay we just had a discussion on this in the Slack channel. It's not obvious and causes a trip hazard for learners. It'd be great if the separate treatment for functions type and module names were explained somewhere, e.g. http://guide.elm-lang.org/types/type_aliases.html. Perhaps http://faq.elm-community.org/ would suffice.

**Comment by evancz** [comment]
All uses of `import Html.App as Html` should be replaced with `import Html.App as App` in the guide. The corresponding changes will be made in the elm-lang.org examples on Monday. I thought I had fixed that already when this issue was opened.

There is also a branch on this repo with a chapter specifically about modules. It still needs work, but that's the direction I'd like to go. I believe that was already underway when this issue was opened as well.

What I was trying to say was, "I understand the problem, and there is work in progress to improve the situation. For now, talk to some community members to get it sorted out. The necessary improvements here are on track."

**Comment by bitterjug** [comment]
> Some of the hardest problems in programming are social:

Too right! Thanks for taking time to explain.

**Comment by gampleman** [comment]
For anyone who wants to know more, see http://stackoverflow.com/questions/38495352/import-html-app-as-html.
