### ISSUE TITLE
Example of invalid arguments in Pattern Matching chapter.... Typo?

### ISSUE THREAD

**Issue by NickSugar** [evancz/guide.elm-lang.org#216]
My experience is as a Junior Full-Stack Dev (mostly Javascript, no functional languages).
Self taught / 6 month immersive program grad.

Elm interests me because I've felt for a while that front-end and web dev in general
has been inefficient and overly complicated since we left pure static HTML pages.
There has to be simpler way, and Elm seems to be a great step in the right direction.
I'm also very interested in learning more about functional languages :)

In the Pattern Matching chapter; I'm confused by the the last paragraph in the Case section.
[https://guide.elm-lang.org/types/pattern_matching.html#case](url)
It states "And if we try invalid arguments like **_toName (Visitor "kate95")_** or toName Anonymous, the compiler tells us about it immediately.".
`toName (Visitor "kate95")` should be valid right? 
The User types Visitor constructor takes a String and the toName function takes a User,
so the "kate95" one should be good to go right? 
Or I could be totally blind and or I'm completely misunderstanding the program ;)

**Comment by evancz** [comment]
Ahh, you are correct! It is supposed to say `toName (Visitar "kate95")` so that it is a typo!

It looks like I messed it up in https://github.com/evancz/guide.elm-lang.org/commit/15bdd721f7801a09cafd2b5584121f5a3b6273b1#diff-6cd2d21bc1d2a87cc0baa26b06476c44, and I just changed it back in https://github.com/evancz/guide.elm-lang.org/commit/af88b4e3e921866930c0d9a1a5f46039d76b6228

Sorry for the trouble!
