### ISSUE TITLE
Please confirm whether this is correct.

### ISSUE THREAD

**Issue by BKSpurgeon** [evancz/guide.elm-lang.org#219]
**- My programming background is ...**

A Ruby on Rails and .net developer.

**- I want to learn Elm because ...**

It looks cool and interesting, and I wanted to know what all the rage about front end frameworks was all about: e.g. React, Angular, Ember, Vue etc. So I settled on Elm.

**- I was confused by ...**

An issue in this page - [the random effect documentation](https://github.com/evancz/guide.elm-lang.org/blob/master/book/effects/random.md):

```elm

type Symbol = Cherry | Seven | Bar | Grapes

symbol : Random.Generator Symbol
symbol =
  Random.uniform Cherry [ Seven, Bar, Grapes ]  -- <------ Consider this line here

{-  Notice how Cherry is outside the array contents, is this correct or is this a  typo? If it's a typo, please comment and I'll make a PR to fix it up. Shouldn't it rather by something like this:  -}

Random.uniform [Cherry, Seven, Bar, Grapes ]  -- notice how Cherry is in the array?

-- Was confused by the documentation.
```

> **Note:** The answers do not have to be super elaborate. I just need to understand who is confused and why. As I learn more about the readers, it is possible to revamp the book that addresses their concerns in a coherent way. Ultimately I must pick an audience, so it fundamentally cannot work for everyone. Choices must be made!

**Comment by fdbeirao** [comment]
Hello @BKSpurgeon. First of all, welcome to Elm. As a fellow .net developer, I hope your journey is also quite pleasant.

Indeed, the example is correct. Notice the signature of the [uniform function](https://package.elm-lang.org/packages/elm/random/latest/Random#uniform):

```elm
uniform : a -> List a -> Generator a
```

My two cents is that the reasoning here is to have a **compile time** guaranteed **non-empty list**. Notice that `List a` can be empty. Then what would it mean to pick a random item from an empty list? Returning `null`? Elm doesn't have `null`s (they are represented as [Maybe](https://guide.elm-lang.org/error_handling/maybe.html)). So if indeed the signature would be "" `uniform : List a -> ??` "" then the return would need to be something like either `Maybe Generator a` or `Generator Maybe a`, which wouldn't be a very pleasant API to work with.

Hence, by enforcing the developer to provide the "head" of the list as a separate argument, the compiler enforces that there exists *at least one* valid return value. The trade-off here is that now the developer needs to be sure not to provide the same item as both the head and a part of the list, otherwise the distribution wouldn't be too uniform anymore :)

Let me know if I can be of further assistance.

Cheers and enjoy!

**Comment by BKSpurgeon** [comment]
@dbeirao many thanks for your explanation.

If I understand it correctly?

```elm
symbol : Random.Generator Symbol
symbol =
  Random.uniform Cherry [  ] -- the List is Empty
-- The default value returned will be Cherry?
-- In other words, developers are forced to fix the problem
-- of empty lists right here. Otherwise we'd have to
-- return Maybes, one way or another?
-- Pls confirm.
```

regards
Ben

**Comment by evancz** [comment]
Yes, exactly. This way the function is guaranteed to get at least one value. So there's never a situation where it doesn't have any values it can generate.
