### ISSUE TITLE
I wasn't sure how to quit the repl

### ISSUE THREAD

**Issue by ericandrewlewis** [evancz/guide.elm-lang.org#68]
The [Get Started](http://guide.elm-lang.org/get_started.html) guide informs the user how to use elm-repl. I followed along but had trouble quitting the repl command line.

**Comment by ericandrewlewis** [comment]
Gosh sorry, I just noticed that this is included at the beginning of the example:

```
$ elm-repl
---- elm-repl 0.17.1 -----------------------------------------------------------
 :help for help, :exit to exit, more at <https://github.com/elm-lang/elm-repl>
--------------------------------------------------------------------------------
```

**Comment by evancz** [comment]
No worries. Where specifically would it be helpful to add a note about this?

If you can quote the text where it should be here, possibly adding a suggestion of the hint that would have helped you, that would be great! Otherwise, it's not clear how to make a change that would have actually helped you.

So I'll close for now, but we can continue discussion here until it is refined into something we can act on. If we get the text, we can potentially turn it into a pull request.

**Comment by crankbird** [comment]
I had the same problem .. I'd gone through a bunch of examples, so by the time I wanted to leave the friendly help you get at the beginning had scrolled off. Being lazy, I just typed, exit,  then bye, then leave and then I tried control-c .. the quality of the error messages in elm made me assume I'd get something like "are you trying to exit repl ? if so try :exit" 

it only took me 10 seconds of googling to find this, so it's not a serious problem, though given the vi like :<command> it might be a nice thing to allow familiar conventions like :q or :x .. or now I come to think of it, maybe even a :w to allow a history or log of the repl output to be saved somewhere :-)

**Comment by Caltor** [comment]
@evancz A reminder here https://guide.elm-lang.org/install.html#elm-repl would be useful. Along the lines of "Once you have finished playing around with elm-repl type :exit and press return to finish."

**Comment by eimfach** [comment]
I had also the same problem ...
I expected typing in 'exit' or 'quit' would give me a hint, I was used to it from other languages repl.
