### ISSUE TITLE
Link from guide directly to this repo, for feedback

### ISSUE THREAD

**Issue by willnwhite** [evancz/guide.elm-lang.org#7]

**Comment by jtojnar** [comment]
Maybe one of these plugins can be used:

* https://plugins.gitbook.com/plugin/github
* https://plugins.gitbook.com/plugin/edit-link
* https://plugins.gitbook.com/plugin/editlink

**Comment by bobbypriambodo** [comment]
+1. With this guide is still being actively developed while being heavily referred to, I think it's great to have a link to this repo in the guide. And while we're at it, probably also a changelog? It kind of throws me off when I get something different each time I visit the guide.

Nevertheless, thanks for the awesome guide!

**Comment by evancz** [comment]
I replied in the PR that came from this: https://github.com/evancz/guide.elm-lang.org/pull/8#issuecomment-285578434

Here is the text reproduced:

> I generally prefer to get feedback on my book by watching people go through it. The reader who is willing to report an issue is a very self-selecting group, and in this case, it is often a beginner who is not yet sure how to express why it is confusing. In person, it is very easy to sort these things out. Online it is very time consuming for both parties.
>
> I have a batch of work scheduled for this book, so whether I am learning about how to improve through in-person "user studies"  or through issues, the work is going to happen all at once.

Hopefully that is not too unsatisfying a response. What I'm trying to say is, the most efficient way to get a great result in the least amount of time (based on my experiences) is not necessarily the route that feels the best to everyone who wants help make it happen. I think of this as a book that I am writing, and there are not issue logs on most books because it's a very bizarre way to chose an editor and guide your future drafts.

**Comment by evancz** [comment]
I created a meta issue #93 to track the things folks find confusing in a coherent way.

Doing this kind of analysis and synthesis is a big part of mining issues into useful insights. It is difficult, and competes with trying to get these insights in other ways.

I tried to talk about all this in a good way in [this talk](https://youtu.be/DSjbTC-hvqQ?t=14m5s).
