### ISSUE TITLE
Elm Guide Translation

### ISSUE THREAD

**Issue by fcevado** [evancz/guide.elm-lang.org#84]
Is there any work/intention on translating this guide to other languages? There are any kind of translation guide or organization structure to contrib with translations(I dont know, something like  a translation folder)? Or just translate it and create another gitbook?

**Comment by rogeriochaves** [comment]
I'd like to help translating it too :)

**Comment by evancz** [comment]
I'm not aware of work on translation, but the book is not "done" so it is possible that it will get a lot more content and be revised quite a bit.

I am really not sure how to approach this because I do not feel comfortable asking folks to do translations when I know that many things would have to be retranslated later. So it feels to early to me. But if people want to do it anyway knowing the situation, I think the way to proceed is to follow the LICENSE and work on it independently.

**Comment by lex111** [comment]
Hello @evancz!

Currently the book is ready for translation? I am translating a book that uses Elm, and as part of this work, I also wanted to translate this official guide. I can do it?
I would also like, if it is possible, that the translation be available at `guide.elm-lang.org/ru`.
I have translation experience (I am the maintainer of the documentation on PHP, React, Vue.js).

**Comment by evancz** [comment]
Folks have been discussing this sort of thing in the #guide-translation channel on the Elm Slack.

There are some folks who have done work on Japanese, and there are people and documents that can help more there.
