### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by adsteel** [evancz/guide.elm-lang.org#90]
I can't find any open issues with any engagement from @evancz, the repo owner. The last merged PR was merged Nov 6, and the last open PR to receive any owner engagement was commented on [July 8th, 2016](https://github.com/evancz/guide.elm-lang.org/pull/20). This is discouraging folks who might want to help solve issues.

Are there any plans to keep this amazing tutorial up to date? If not, is there a willingness to hand it over to a person or organization who has motivation to keep it going?

I personally believe this resource, or something like it, will be a critical part of Elm maintaining a healthy community and not fading into obscurity.

**Comment by evancz** [comment]
Please watch [this talk](https://youtu.be/DSjbTC-hvqQ?t=14m5s) to learn more about how I work. Specifically about batching work.

Yes, I plan to continue working on this tutorial. After 0.19 is out I will be adding a bunch of sections and revising the existing ones. My work style involves *batching* this work to increase throughput (at the cost of latency) which is what you are seeing here.

**Comment by evancz** [comment]
Sorry about how aggressive that sounds. I am going through a bunch of issues and PRs now. You can look through them [here](https://github.com/evancz/guide.elm-lang.org/pulls?utf8=%E2%9C%93&q=sort%3Aupdated-desc%20). Often there is an editorial component that makes these quite difficult to review. It is rare that someone just fixes a link.

In other words, it's more complex than it looks. Many of these issues don't have quick fixes, and sometimes the fix is "the language or the ecosystem needs to be better" which cannot be addressed by changing the guide.
